### ISSUE TITLE
Maintenance and new releases

### ISSUE THREAD

**Issue by einhverfr** [infofarmer/hashtypes#7]
Hi;

At Adjust we have fixed a few issues we have found with this extension.  I have noticed that our PRs have not gotten any traction or even responses.  Some of these include fixes for things like join estimates.

Any objection to us releasing 0.1.2 and 0.1.3 on pgxn?  Since you have released 0.1.1 figured it would be good to ask first.

**Comment by andreypopp** [comment]
Hi,

Sorry I've been away from PostgreSQL extension developing for a while so can't take the responsibility to verify and merge the PRs.

I think we need to add more collaborators to the repo, what do you think @infofarmer?

**Comment by einhverfr** [comment]
I am not seeing any maintenance on this since 2013 which is why I am asking.  If you folks would like help we would be happy to help :-)

**Comment by andreypopp** [comment]
Totally, sorry for that.

The @infofarmer is the one who has rights to add the collaborators.

**Comment by infofarmer** [comment]
GitHub is a joke. 2FA broke for me months ago. Feel free to fork ☺️

**Comment by andreypopp** [comment]
Ok, the fork is the right way then.

@einhverfr I have access to pgxn account which was used to make releases. You can fork the repo and we'll figure out how to transfer ownership of the package on pgxn then.

**Comment by einhverfr** [comment]
I work on the adjust fork (along with the authors of the two current PRs).

I will be happy to reach out to the aleksabl as well.

**Comment by einhverfr** [comment]
My pgxn account is also einhverfr if that helps.  By the way, we also have travis testing up for this through Pg 10 and one of the major things we fixed was join estimates where a join is done across a hash type.

**Comment by einhverfr** [comment]
As a note, I have placed a request in for how one goes about reassigning this into the pgxn list.  WIll post back here when I hear of anything.  I dont think this can be done through the PGXN manager at present.

**Comment by andreypopp** [comment]
@einhverfr I think pgxn is ok now. Do you want me to update the README to point to your fork so that people don't get confused?
